### ISSUE TITLE
Add todo-app for baseline

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/tutorial-apps#1]
## Description
See https://github.com/terasolunaorg/guideline/issues/1557
It's better to include optional assignments shown http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/TutorialTodo/index.html#id41

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] based_5.1.0_single_jpa
- [x] based_5.1.0_single_mybatis3
- [x] based_5.1.0_multi_jpa
- [x] based_5.1.0_multi_mybatis3

each project is generated by ``generate-app-project.sh``

**Comment by ikeyat** [comment]
- [ ] Please a parent shell script that aggregates separated shell scripts.

**Comment by ikeyat** [comment]
follow directory structure https://github.com/terasolunaorg/tutorial-apps/pull/11#issuecomment-186806124
 - [ ] todo
 - [ ] todo-rest
 - [ ] first-security
