### ISSUE TITLE
Modify loginForm.jsp indent adjust 4 spaces in spring security tutorial app jsp source

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/tutorial-apps#179]
## Description
details see terasolunaorg/guideline#3267

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)
- [x] 5.4.2 (5.4.x)
- [x] 5.3.2 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x) not requiered. Because only rename login.jsp -> loginForm.jsp at #174.
- [x] 1.0.7 (1.0.x) not requiered. Because only rename login.jsp -> loginForm.jsp at #174.
- [x] 1.6.0 (m-j/master)
- [x] 1.6.0 (m-t/master)  in terasolunaorg/tutorial-apps#177.

## Final Solution
(To be written later by project member)

## Issue Links
* terasolunaorg/guideline#3267
* #174

**Comment by yoshikawaa** [comment]
@hosoitk English version remaining.
