### ISSUE TITLE
Add todo-api-app for baseline

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/tutorial-apps#2]
## Description
See https://github.com/terasolunaorg/guideline/issues/1557

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] based_5.1.0_single_jpa
- [x] based_5.1.0_single_mybatis3
- [x] based_5.1.0_multi_jpa
- [x] based_5.1.0_multi_mybatis3

**Comment by ikeyat** [comment]
Done by #4.
