### ISSUE TITLE
Unnecessary login.jsp remains

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/tutorial-apps#246]
## Description
Just below webapp folder have login.jsp.
But login.jsp moved by #174. So delete login.jsp.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master) not requiered.  login.jsp Deleted by #174.
- [x] 5.4.2 (5.4.x)  not requiered.  login.jsp Deleted by #174.
- [x] 5.3.2 (5.3.x)  not requiered.  login.jsp Deleted by #174.
- [x] 5.2.2 (5.2.x)  not requiered.  login.jsp Deleted by #174.
- [x] 5.1.2 (5.1.x)  not requiered.  login.jsp Deleted by #174.
- [x] 5.0.3 (5.0.x)  not requiered.  login.jsp Deleted by #174.
- [x] 1.0.7 (1.0.x) 
- [x] 1.6.0 (m-j/master)  not requiered.  login.jsp Deleted by #174.
- [ ] 1.5.2 (m-j/1.5.x) 1.5.x branch doesn't exsist as of 2018/03/06. The project member decides later whether to create the 1.5.x branch.
- [x] 1.6.0 (m-t/master) not requiered.  login.jsp Deleted by terasolunaorg/guideline#177.

## Final Solution
(To be written later by project member)

## Issue Links
* #174

**Comment by yoshikawaa** [comment]
Proberbly m-j/1.5.x will be fixed at #174.
